"""baseline producao

Revision ID: a13c9cd7e7fb
Revises: 
Create Date: 2026-09-19 14:34:51.914778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13c9cd7e7fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('igrejas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('presidente', sa.String(length=150), nullable=False),
    sa.Column('endereco', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atividades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=True),
    sa.Column('local', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('igreja_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['igreja_id'], ['igrejas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=250), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('igreja_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['igreja_id'], ['igrejas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('igreja_id', 'nome', name='uq_funcao_igreja_nome')
    )
    op.create_table('membros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('contato', sa.String(length=20), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('logradouro', sa.String(length=180), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('referencia', sa.String(length=200), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('igreja_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['igreja_id'], ['igrejas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=250), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('igreja_id', sa.Integer(), nullable=False),
    sa.Column('lider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['igreja_id'], ['igrejas.id'], ),
    sa.ForeignKeyConstraint(['lider_id'], ['membros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('igreja_id', 'nome', name='uq_grupo_igreja_nome')
    )
    op.create_table('membro_funcoes',
    sa.Column('membro_id', sa.Integer(), nullable=False),
    sa.Column('funcao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funcao_id'], ['funcoes.id'], ),
    sa.ForeignKeyConstraint(['membro_id'], ['membros.id'], ),
    sa.PrimaryKeyConstraint('membro_id', 'funcao_id')
    )
    op.create_table('movimentacoes_financeiras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=250), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=30), nullable=True),
    sa.Column('data_movimentacao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('igreja_id', sa.Integer(), nullable=False),
    sa.Column('membro_id', sa.Integer(), nullable=True),
    sa.Column('atividade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividades.id'], ),
    sa.ForeignKeyConstraint(['igreja_id'], ['igrejas.id'], ),
    sa.ForeignKeyConstraint(['membro_id'], ['membros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presencas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('registrado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('membro_id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividades.id'], ),
    sa.ForeignKeyConstraint(['membro_id'], ['membros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membro_id', 'atividade_id', name='uq_presenca_membro_atividade')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=30), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('igreja_id', sa.Integer(), nullable=True),
    sa.Column('membro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['igreja_id'], ['igrejas.id'], ),
    sa.ForeignKeyConstraint(['membro_id'], ['membros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membro_id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    op.create_table('membro_grupos',
    sa.Column('membro_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['membro_id'], ['membros.id'], ),
    sa.PrimaryKeyConstraint('membro_id', 'grupo_id')
    )
    op.create_table('tarefas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('prioridade', sa.String(length=20), server_default='normal', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pendente', nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=True),
    sa.Column('local', sa.String(length=150), nullable=True),
    sa.Column('gerar_atividade', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.Column('igreja_id', sa.Integer(), nullable=False),
    sa.Column('funcao_id', sa.Integer(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('membro_id', sa.Integer(), nullable=True),
    sa.Column('atividade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['atividades.id'], ),
    sa.ForeignKeyConstraint(['funcao_id'], ['funcoes.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['igreja_id'], ['igrejas.id'], ),
    sa.ForeignKeyConstraint(['membro_id'], ['membros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atividade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarefas')
    op.drop_table('membro_grupos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('presencas')
    op.drop_table('movimentacoes_financeiras')
    op.drop_table('membro_funcoes')
    op.drop_table('grupos')
    op.drop_table('membros')
    op.drop_table('funcoes')
    op.drop_table('atividades')
    op.drop_table('igrejas')
    # ### end Alembic commands ###
